services:
  docs:
    image: outfit_finder_local_docs
    container_name: outfit_finder_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - path: ./.envs/.local/.django
        required: false
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./outfit_finder:/app/outfit_finder:z
    ports:
      - '9000:9000'
    command: /start-docs
