# Generated by Django 6.0.8 on 2026-08-31 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Etiket/Tarz')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kıyafet Adı')),
                ('image', models.ImageField(upload_to='clothing_images/', verbose_name='Fotoğraf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='clothes', to='catalog.styletag')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Mağaza Adı (Trendyol, Zara vb.)')),
                ('url', models.URLField(max_length=500, verbose_name='Ürün Linki')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('is_affiliate', models.BooleanField(default=True, verbose_name='Affiliate Linki mi?')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Fiyat Güncellemesi')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.clothingitem')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kombin Adı')),
                ('image', models.ImageField(upload_to='outfit_images/', verbose_name='Kombin Fotoğrafı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_outfits', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='outfits', to='catalog.clothingitem', verbose_name='Kullanılan Kıyafetler')),
                ('tags', models.ManyToManyField(blank=True, related_name='outfits', to='catalog.styletag')),
            ],
        ),
    ]
