# Generated by Django 6.0.8 on 2026-09-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlink',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
