# Generated by Django 6.0.8 on 2026-09-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_itemlink_last_checked_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='added_by',
            new_name='creator',
        ),
    ]
